### ISSUE TITLE
Select tr failed when try to parse specific problem

### ISSUE THREAD

**Issue by weeebdev** [dianhsu-official/ace#17]
<img width="168" alt="image" src="https://github.com/dianhsu-official/ace/assets/48881444/2972cdfe-a967-4f2c-bbcd-9dcf09c1b0f8">

**Comment by weeebdev** [comment]
<img width="594" alt="image" src="https://github.com/dianhsu-official/ace/assets/48881444/fd3d7986-a665-4787-8f1f-c2bf43d88aea">
<img width="270" alt="image" src="https://github.com/dianhsu-official/ace/assets/48881444/8966c4c1-fa0c-48c5-82fe-aab6bbce6448">
It seems that cli is not working properly for now

**Comment by dianhsu** [comment]
Thank you for your testing, I will take a look tonight.

**Comment by dianhsu** [comment]
> <img alt="image" width="168" src="https://private-user-images.githubusercontent.com/48881444/292774003-2972cdfe-a967-4f2c-bbcd-9dcf09c1b0f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzk2ODUsIm5iZiI6MTcwMzU3OTM4NSwicGF0aCI6Ii80ODg4MTQ0NC8yOTI3NzQwMDMtMjk3MmNkZmUtYTk2Ny00ZjJjLWJiY2QtOWRjZjA5YzFiMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0N2FkMWQxMjUwNDQzZjQxNWQ2MDE0ZjkzN2JjYzkzYWMxNDJiNmNhOTFkNWQyZjIyNGNhNTliNGYyYWEyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KDqhtjxWW_Axy2QvgIV6z7OvNaAfomyh4NWQYGlVo5E">

For this error, `parse` command should follow contest id.

**Comment by weeebdev** [comment]
> > <img alt="image" width="168" src="https://private-user-images.githubusercontent.com/48881444/292774003-2972cdfe-a967-4f2c-bbcd-9dcf09c1b0f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzk2ODUsIm5iZiI6MTcwMzU3OTM4NSwicGF0aCI6Ii80ODg4MTQ0NC8yOTI3NzQwMDMtMjk3MmNkZmUtYTk2Ny00ZjJjLWJiY2QtOWRjZjA5YzFiMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0N2FkMWQxMjUwNDQzZjQxNWQ2MDE0ZjkzN2JjYzkzYWMxNDJiNmNhOTFkNWQyZjIyNGNhNTliNGYyYWEyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KDqhtjxWW_Axy2QvgIV6z7OvNaAfomyh4NWQYGlVo5E">
> 
> For this error, `parse` command should follow contest id.

I cannot parse specific problem?

**Comment by dianhsu** [comment]
currently, Yes！it only support parse whole contest

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Adil Akhmetov ***@***.***>
发送时间: Tuesday, December 26, 2023 4:59:49 PM
收件人: dianhsu-official/ace ***@***.***>
抄送: dianhsu ***@***.***>; Comment ***@***.***>
主题: Re: [dianhsu-official/ace] Select tr failed when try to parse specific problem (Issue #17)


[image]<https://private-user-images.githubusercontent.com/48881444/292774003-2972cdfe-a967-4f2c-bbcd-9dcf09c1b0f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzk2ODUsIm5iZiI6MTcwMzU3OTM4NSwicGF0aCI6Ii80ODg4MTQ0NC8yOTI3NzQwMDMtMjk3MmNkZmUtYTk2Ny00ZjJjLWJiY2QtOWRjZjA5YzFiMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0N2FkMWQxMjUwNDQzZjQxNWQ2MDE0ZjkzN2JjYzkzYWMxNDJiNmNhOTFkNWQyZjIyNGNhNTliNGYyYWEyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KDqhtjxWW_Axy2QvgIV6z7OvNaAfomyh4NWQYGlVo5E>

For this error, parse command should follow contest id.

I cannot parse specific problem?

―

**Comment by dianhsu** [comment]
> <img alt="image" width="594" src="https://private-user-images.githubusercontent.com/48881444/292774197-fd3d7986-a665-4787-8f1f-c2bf43d88aea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDQ5OTEsIm5iZiI6MTcwMzYwNDY5MSwicGF0aCI6Ii80ODg4MTQ0NC8yOTI3NzQxOTctZmQzZDc5ODYtYTY2NS00Nzg3LThmMWYtYzJiZjQzZDg4YWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE1MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMzU4MGNmYWVmN2VjYjMxYTEyYWQ0NDBmNDljMDNkOTExMzY4MjE4NzQxYmQ5YTI2NjE4N2RkMzZiYmQ4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b40jO7meg7Yc3lWHPhe8XIaxJybSp23m0gDaU5uN1MA"> <img alt="image" width="270" src="https://private-user-images.githubusercontent.com/48881444/292774182-8966c4c1-fa0c-48c5-82fe-aab6bbce6448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDQ5OTEsIm5iZiI6MTcwMzYwNDY5MSwicGF0aCI6Ii80ODg4MTQ0NC8yOTI3NzQxODItODk2NmM0YzEtZmEwYy00OGM1LTgyZmUtYWFiNmJiY2U2NDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE1MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwOTFhYWU1OWY4OTQ4MzMyZDUxYWJkNjE2NzY1YTYxOWFlYTZhOTMyZTBlNzNjY2I3NjU1YjU2OGJiYjQwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hWKNCECm8dHIm4DO4gTsLCJgQFBmYvG76S6RCBwZeVA"> It seems that cli is not working properly for now

The issue in first picture has been addressed and solved in this PR.
